spring:
  security:
    user:
      name: ${PICTURE_SERVICE_USR_NAME:picture_service_user}
      password: ${PICTURE_SERVICE_USER_PASSWORD:password}
      roles:
        - SERVICE
  application:
    name: picture_service
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/pictures-api
    username: postgres
    password: postgres
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: group-id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
service:
    storage:
      username: storage_service_user
      password: password
      url:
        base: '${URL_STORAGE_SERVICE:http://172.17.0.2:8081}'
        upload: '${METHOD_UPLOAD_FILE:/upload}'
        files:  '${METHOD_GET_FILE:/files}'
