spring:
  application:
    name: picture_service
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/pictures-api
    username: postgres
    password: postgres

url:
  service:
      storage:
        base: '${URL_STORAGE_SERVICE:http://172.17.0.2:8081}'
        upload: '${METHOD_UPLOAD_FILE:/upload}'
        files:  '${METHOD_GET_FILE:/files}'