spring:
  application:
    name: picture_service
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/pictures-api
    username: postgres
    password: postgres